version: "3.7"

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile

    # nodemon이 도커에도 적용되게 한다.
    # [로컬 컴퓨터]:[도커 컴퓨터]
    volumes:
      - ./index.js:/myfolder/index.js
      - ./email.js:/myfolder/email.js
    ports:
      - 3000:3000

  my-database:
    # dockerfile 없이 바로 yaml에서 도커 이미지 설치
    image: mongo:5
    ports:
      - 27017:27017
